#!/usr/bin/env python3
"""Generate c/triton_report_desc.h from the captured raw sysfs report_descriptor.

Reads docs/superpowers/captures/triton-usb-capture-raw.txt, extracts the hex bytes
in the '=== sysfs report_descriptor (od -tx1) ===' section (between 'FILE:' and the
trailing '---'), and emits a byte-exact C array. Deterministic: no hand transcription.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[3]   # .../steamcontroller-test
RAW  = ROOT / "docs/superpowers/captures/triton-usb-capture-raw.txt"
OUT  = ROOT / "tools/triton-usbip/c/triton_report_desc.h"

text = RAW.read_text(errors="replace")

# Isolate the sysfs report_descriptor section.
m = re.search(r"sysfs report_descriptor.*?FILE:.*?\n(.*?)\n---", text, re.S)
if not m:
    sys.exit("could not find sysfs report_descriptor section in raw capture")
body = m.group(1)
# Drop the 'SIZE: N bytes' line; keep only hex byte rows.
hexbytes = []
for line in body.splitlines():
    line = line.strip()
    if not line or line.upper().startswith("SIZE"):
        continue
    if not re.fullmatch(r"(?:[0-9a-fA-F]{2}\s*)+", line):
        continue
    hexbytes += [int(b, 16) for b in line.split()]

n = len(hexbytes)
if n != 372:
    sys.stderr.write("WARNING: expected 372 bytes, got %d\n" % n)

lines = []
for i in range(0, n, 12):
    chunk = hexbytes[i:i+12]
    lines.append("    " + " ".join("0x%02X," % b for b in chunk))

hdr = """/* triton_report_desc.h — GENERATED by tools/triton-usbip/win/gen_report_desc.py
 * Byte-exact HID Report Descriptor of the genuine 2026 Steam Controller (Triton),
 * VID 0x28DE / PID 0x1302, captured off real hardware via usbipd->WSL sysfs.
 * %d bytes. DO NOT hand-edit; regenerate from the raw capture instead.
 *
 * Report-ID map (numbered reports):
 *   0x40 mouse (lizard)     0x41 keyboard (lizard)
 *   0x42 vendor state IN  (53B)   0x45 vendor state IN BLE-style (45B)
 *   0x43/0x44/0x79/0x7B vendor status IN
 *   0x80..0x89 vendor OUT      0x01/0x02 vendor FEATURE (63B)
 */
#ifndef TRITON_REPORT_DESC_H
#define TRITON_REPORT_DESC_H

#define TRITON_REPORT_DESC_LEN %d
static const unsigned char triton_report_desc_bytes[TRITON_REPORT_DESC_LEN] = {
%s
};

#endif /* TRITON_REPORT_DESC_H */
""" % (n, n, "\n".join(lines))

OUT.write_text(hdr)
print("wrote %s (%d bytes)" % (OUT, n))
